### PR TITLE
Clarify docs for migration of ipam coupling to dnssync

### PR DESCRIPTION
**Pull request by Stathogon**
Hello,
i just migrated my netbox to use DNSSync and was a bit confused what to do with the custom fields. Added a Clarification to the docs so it is easier to see.

### CODE REVIEW

**Review by peteeckel — CHANGES_REQUESTED** [review]
Hi @Stathogon, thanks for this! It's always difficult to write documentation for things you don't need documented for yourself, so this is valuable input.

Could you please just remove the extraneous whitespace between "to the" and "new IPAM DNSSync"?

**Comment by Stathogon** [comment]
i edited the file in the Commit? im not to familiar with git/github, i hope it achieved what i wanted. Atleast for me it looks fine now

**Review by peteeckel — APPROVED** [review]
Yep, thanks!

**Comment by peteeckel** [comment]
Generally, if you want to make changes to a PR it's sufficient to change files in your local repository, commit and pust to GitHub again.

**Pull request merged**
