### PR TITLE
Add journal tab

### PR DESCRIPTION
**Pull request by squintfox**
Adds Journal for Record, Zone, Registrar and Contact models.  Fixes [#121](https://github.com/peteeckel/netbox-plugin-dns/issues/121).

### CODE REVIEW

**Comment by squintfox** [comment]
I missed the formatting piece. I'll go back and correct.

**Comment by peteeckel** [comment]
Hi @squintfox, 

thanks for the PR! 

Some small issues:
* Linting failed. Please run black on the files you touched to make the code style consistent
* Why did you exclude the `View` and `Nameserver` models? I'd prefer to have it fully consistent - Journals are a good idea!

**Comment by squintfox** [comment]
@peteeckel No particular reason that I excluded them, just couldn't really think of a use case of why they'd get used.  No big deal though, I'll go back and add the rest.  Sorry about linting, I got that corrected.

**Comment by squintfox** [comment]
@peteeckel Should be all set now.

**Comment by peteeckel** [comment]
Awesome, thank you very much!

0.21.10 is on its way :-)

**Pull request merged**
